language: php

php:
  - hhvm	
  - 5.6
  - 7

services:
  - mysql

before_script:
  # Update Composer
  - composer self-update
  # Install
  - composer install
  - mysql -e 'create database deployer;'
script:
  - vendor/phpunit/phpunit/phpunit -c ./ --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
